Add discovery and custom install support
Signed-off-by: Oleg Bulatov <oleg@bulatov.me>

diff --git a/hm/files/bin/hm-make b/hm/files/bin/hm-make
--- a/hm/files/bin/hm-make
+++ b/hm/files/bin/hm-make
@@ -1,47 +1,43 @@
 #!/bin/bash
+# vim: set ts=4 sts=4 sw=4 noet :
 set -euo pipefail
 
 E_OPTERROR=85
 
-FAKE_TMP_DIR=$(mktemp -d -t hm-make.XXXXXXXXXX)
-FAKE_ROOT="${FAKE_TMP_DIR}/root"
-FAKE_INDEX="${FAKE_TMP_DIR}/index"
-FAKE_FILES_DIR="${FAKE_TMP_DIR}/files"
-
 while getopts ":r:l:h:" Option; do
 case $Option in
 r)
-    REAL_ROOT=$OPTARG
-    ;;
+	REAL_ROOT=$OPTARG
+	;;
 l)
-    REAL_LOGIN=$OPTARG
-    ;;
+	REAL_LOGIN=$OPTARG
+	;;
 h)
-    REAL_HOST=$OPTARG
-    ;;
+	REAL_HOST=$OPTARG
+	;;
 esac
 done
 shift $(($OPTIND - 1))
 
 if [ $# -eq 0 ]; then
-    echo "Usage: $0 [-r ROOT] [-l LOGIN] [-h HOSTNAME] packages..." >&2
-    exit $E_OPTERROR
+	echo "Usage: $0 [-r ROOT] [-l LOGIN] [-h HOSTNAME] packages..." >&2
+	exit $E_OPTERROR
 fi
 
 . "$(dirname "$(test -L "$0" && readlink "$0" || echo "$0")")/hm-funcs.bash"
 
 if [ "x${REAL_ROOT:-}" = "x" ]; then
-    eval "$(
-        (
-echo "printf 'REAL_ROOT=%q\n' \$HOME"
-        ) | real_bash
-    )"
-    if [ "x${REAL_ROOT:-}" = "x" ]; then
-        echo "$0: Unable to discover \$HOME value. Use -r ROOT option." >&2
-        exit 1
-    else
-        echo "$(prefix ">>>") Discovered ROOT: $REAL_ROOT"
-    fi
+	eval "$(
+		(
+			echo "printf 'REAL_ROOT=%q\n' \$HOME"
+		) | real_bash
+	)"
+	if [ "x${REAL_ROOT:-}" = "x" ]; then
+		echo "$0: Unable to discover \$HOME value. Use -r ROOT option." >&2
+		exit 1
+	else
+		echo "$(prefix ">>>") Discovered ROOT: $REAL_ROOT"
+	fi
 fi
 
 REAL_HM_DIR="$REAL_ROOT/.hm"
@@ -52,15 +48,17 @@ REAL_BACKUP_FILES_DIR="$REAL_HM_DIR/backup/files/$(date +%Y%m%d-%H%M%S)"
 
 PKGS=("$@")
 
-rm -rf "$FAKE_FILES_DIR" && mkdir -p "$FAKE_FILES_DIR"
-rm -rf "$FAKE_ROOT" && mkdir -p "$FAKE_ROOT"
-rm -f "$FAKE_INDEX"
 for PKG in "${PKGS[@]}"; do
-    install_pkg "$PKG"
+	schedule_pkg "$PKG"
 done
+
+real_discover
+
+fake_init
+fake_install
 
 rsync_files_dir
 rsync_root
 rsync_index
 
-cleanup
+fake_cleanup
