Fix hm-make for Mac OS X
Signed-off-by: Oleg Bulatov <oleg@bulatov.me>

diff --git a/hm/files/bin/hm-make b/hm/files/bin/hm-make
--- a/hm/files/bin/hm-make
+++ b/hm/files/bin/hm-make
@@ -3,7 +3,7 @@ set -euo pipefail
 
 E_OPTERROR=85
 
-FAKE_TMP_DIR=$(mktemp -d --tmpdir hm-make.XXXXXXXXXX)
+FAKE_TMP_DIR=$(mktemp -d -t hm-make.XXXXXXXXXX)
 FAKE_ROOT="${FAKE_TMP_DIR}/root"
 FAKE_INDEX="${FAKE_TMP_DIR}/index"
 FAKE_FILES_DIR="${FAKE_TMP_DIR}/files"
@@ -31,13 +31,13 @@ fi
 . "$(dirname "$(test -L "$0" && readlink "$0" || echo "$0")")/hm-funcs.bash"
 
 if [ "x${REAL_ROOT:-}" = "x" ]; then
-    . <(
-    (
-echo "printf 'REAL_ROOT=%q' \$HOME"
-    ) | real_bash
-    )
+    eval "$(
+        (
+echo "printf 'REAL_ROOT=%q\n' \$HOME"
+        ) | real_bash
+    )"
     if [ "x${REAL_ROOT:-}" = "x" ]; then
-        echo "$0: Unable to discover right \$HOME value. Use -r ROOT option." >&2
+        echo "$0: Unable to discover \$HOME value. Use -r ROOT option." >&2
         exit 1
     else
         echo "$(prefix ">>>") Discovered ROOT: $REAL_ROOT"
