Update hm package
Signed-off-by: Oleg Bulatov <oleg@bulatov.mobi>

diff --git a/hm/files/bin/hm-make b/hm/files/bin/hm-make
--- a/hm/files/bin/hm-make
+++ b/hm/files/bin/hm-make
@@ -8,10 +8,13 @@ FAKE_ROOT="${FAKE_TMP_DIR}/root"
 FAKE_INDEX="${FAKE_TMP_DIR}/index"
 FAKE_FILES_DIR="${FAKE_TMP_DIR}/files"
 
-while getopts ":r:h:" Option; do
+while getopts ":r:l:h:" Option; do
 case $Option in
 r)
     REAL_ROOT=$OPTARG
+    ;;
+l)
+    REAL_LOGIN=$OPTARG
     ;;
 h)
     REAL_HOST=$OPTARG
@@ -20,9 +23,25 @@ esac
 done
 shift $(($OPTIND - 1))
 
-if [ "x${REAL_ROOT:-}" = "x" -o $# -eq 0 ]; then
-    echo "Usage: $0 -r ROOT [-h HOSTNAME] packages..." >&2
+if [ $# -eq 0 ]; then
+    echo "Usage: $0 [-r ROOT] [-l LOGIN] [-h HOSTNAME] packages..." >&2
     exit $E_OPTERROR
+fi
+
+. "$(dirname "$(test -L "$0" && readlink "$0" || echo "$0")")/hm-funcs.bash"
+
+if [ "x${REAL_ROOT:-}" = "x" ]; then
+    . <(
+    (
+echo "printf 'REAL_ROOT=%q' \$HOME"
+    ) | real_bash
+    )
+    if [ "x${REAL_ROOT:-}" = "x" ]; then
+        echo "$0: Unable to discover right \$HOME value. Use -r ROOT option." >&2
+        exit 1
+    else
+        echo "$(prefix ">>>") Discovered ROOT: $REAL_ROOT"
+    fi
 fi
 
 REAL_HM_DIR="$REAL_ROOT/.hm"
@@ -32,8 +51,6 @@ REAL_BACKUP_ROOT="$REAL_HM_DIR/backup/root/$(date +%Y%m%d-%H%M%S)"
 REAL_BACKUP_FILES_DIR="$REAL_HM_DIR/backup/files/$(date +%Y%m%d-%H%M%S)"
 
 PKGS=("$@")
-
-. hm-funcs.bash
 
 rm -rf "$FAKE_FILES_DIR" && mkdir -p "$FAKE_FILES_DIR"
 rm -rf "$FAKE_ROOT" && mkdir -p "$FAKE_ROOT"
